config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :cryptos
  devise_for :users
  root 'home#about'

  get 'home/about'
  get 'home/lookup'
  post 'home/lookup' => 'home/lookup'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
    has_many :purchases, dependent: :destroy
    has_many :users
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :user
    belongs_to :crypto
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cryptos
  has_many :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        cryptos_path
      end
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @portfolio_profit = 0
    @cryptos = Crypto.where(user_id: current_user.id)

    @file = File.join(Rails.root, "app", "assets", "images")

    #Connects to API
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    headers = {
        'X-CMC_PRO_API_KEY': '571099ec-2545-49b6-84dc-432d3a2d3c3b',
    }
    
    response = HTTParty.get(url, headers: headers)
    coins = JSON.parse(response.body)
    @crypto_coins = coins['data']
  end

  def show
    @purchases = Purchase.where(user_id: current_user.id,crypto_id: params[:id])
    p @purchases
  end

  def new
    @crypto = current_user.cryptos.build
  end

  def edit
  end

  def create
    @crypto = current_user.cryptos.build(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :cost_per, :amount_owned)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    headers = {
        'X-CMC_PRO_API_KEY': '571099ec-2545-49b6-84dc-432d3a2d3c3b',
    }
    
    response = HTTParty.get(url, headers: headers)
    coins = JSON.parse(response.body)
    @coins = coins['data']

  end
  
  def about
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    headers = {
        'X-CMC_PRO_API_KEY': '571099ec-2545-49b6-84dc-432d3a2d3c3b',
    }
    
    response = HTTParty.get(url, headers: headers)
    coins = JSON.parse(response.body)
    @coins = coins['data']
  end
  
  def lookup
    @symbol = params[:symbol]
    @symbol ? @symbol.upcase! : nil
    @symbol == '' ? @symbol = 'Please enter a currency to lookup' : nil


    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    headers = {
        'X-CMC_PRO_API_KEY': '571099ec-2545-49b6-84dc-432d3a2d3c3b',
    }
    
    response = HTTParty.get(url, headers: headers)
    coins = JSON.parse(response.body)
    @lookup_coin = coins['data']
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_file, only: [:index, :show, :update]

  def index
    @purchases = Purchase.where(user_id: current_user.id)


  end

  def show
  end

  def new
    @purchase = current_user.purchases.build
  end

  def edit
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user = current_user
    @purchase.symbol.upcase!
    # @crypto = ''
    # Determine which crypto the currency belongs to
    cryptos = Crypto.where(user_id: current_user.id)
    for crypto in cryptos
      if crypto.symbol == @purchase.symbol
        @purchase.crypto_id = crypto.id
      end
    end

    # If there is no crypto it belongs to, it creates a new one
    if !@purchase.crypto_id.present?
      @crypto = current_user.cryptos.build(symbol: @purchase.symbol, amount_owned: 0, cost_per: 0)
      @crypto.save!
      @purchase.crypto_id = @crypto.id
    end

    respond_to do |format|
      if @purchase.save
        update_crypto(@purchase)

        # @crypto = Crypto.where(user_id: current_user.id, id: @purchase.crypto_id)
        # p '****************'
        # p @crypto
        # p '//////////'
        # p @crypto.amount_owned

        # Update the crypto variables
        # @crypto.amount_owned += @purchase.amount
        # @crypto.cost_per += ((@purchase.total_cost) / (@purchase.amount))


        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    def purchase_params
      params.require(:purchase).permit(:symbol, :cost_per, :amount, :fee, :total_cost, :description)
    end

    def update_crypto(purchase)
      cryptos = Crypto.where(user_id: current_user.id)
      for crypto in cryptos
        if crypto.symbol == @purchase.symbol
          @crypto = crypto
          @crypto_total_cost = @crypto.cost_per * @crypto.amount_owned
        end
      end

      if purchase.description == 'Buy'
        @crypto_total_cost += @purchase.total_cost
        @crypto.amount_owned += purchase.amount
        @crypto_new_total_cost = @crypto_total_cost / @crypto.amount_owned
        @crypto.cost_per = @crypto_new_total_cost
        @crypto.save!
      else
        @crypto_total_cost -= @purchase.total_cost
        @crypto.amount_owned -= purchase.amount
        @crypto_new_total_cost = @crypto_total_cost / @crypto.amount_owned
        @crypto.cost_per = @crypto_new_total_cost
        @crypto.save!




        # @crypto.amount_owned -= purchase.amount
      

        # The math doesn't work properly for selling
        # @crypto.cost_per -= ((purchase.total_cost)/(purchase.amount))
      end
      @crypto.save!
    end

    def set_file
      @file = File.join(Rails.root, "app", "assets", "images")
    end
end


# How to update it???!!

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/cryptos/_form.html.erb
<div class='purchase-form'>
  <div class='purchase-form-container'>
    <div class=purchase-form-form>
      
      <% if crypto.new_record? %>
        <h2>New Cryptocurrency</h2>
      <% else %>
        <h2>Edit Cryptocurrency</h2>
      <% end %>

      <%= form_with(model: crypto, local: true) do |form| %>
        <% if crypto.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

            <ul>
              <% crypto.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <label>Cryptocurrency Symbol</label>
          <%= form.text_field :symbol, placeholder: 'Eg, BTC, XRP, LTC..' %>
        </div>

        <div class="field">
          <label>Amount of Crypto</label>
          <%= form.text_field :amount_owned, placeholder: 'How much do you own?' %>
        </div>

        <div class="field">
          <label>Cost per Crypto</label>
          <%= form.text_field :cost_per, placeholder: 'What was the average price you paid?' %>
        </div>

        <div class="actions">
          <% if crypto.new_record? %>
            <%= form.submit 'Create Crypto', class: 'purchase-form-btn', id: 'purchase-form-btn' %>
            <p>Don't wait to create a crypto? <a href="<%= cryptos_path %>">Go Back</a></p>
          <% else %>
            <%= form.submit 'Edit Crypto', class: 'purchase-form-btn', id: 'purchase-form-btn' %>
            <p>Don't wait to edit this Crypto? <a href="<%= crypto_path(crypto) %>">Go Back</a></p>
          <% end%>
        </div>
        </div>
      <% end %>
  </div>
</div>

app/views/cryptos/edit.html.erb
<%= render 'form', crypto: @crypto %>

app/views/cryptos/index.html.erb
<div class='crypto-bg'>
  
  <div class='crypto-summary'>
    <% for crypto in @cryptos %>
      <div class='individual-crypto'>
        <div>
        <%# Image %>
        <% if File.exist?("#{@file}/color/#{crypto.symbol.downcase}.png") %>
            <%= image_tag("color/#{crypto.symbol.downcase}.png", :class => 'purchase-img img-title')%>
        <% end %>

        <% @crypto_coins.each do |crypto_coin| %>
          <% if crypto.symbol == crypto_coin['symbol'] %>
            <%# Crypto Name %>
            <%= crypto_coin['name'] %>
            </div>

            <div>
              <p>USD $<%= crypto_coin['quote']['USD']['price'].round(4) %></p>
            </div>

            <div class='crypto-movement'>
              <%# 1 Hr Change %>
              <% if (crypto_coin['quote']['USD']['percent_change_1h']) >= 0 %>
                <p><span class='up'><i class='fas fa-arrow-up' ></i>
                <%= (crypto_coin['quote']['USD']['percent_change_1h']).round(2) %>%</span> 1H</p>
              <% else%>
                <p><span class='down'><i class='fas fa-arrow-down' ></i>
                <%= (crypto_coin['quote']['USD']['percent_change_1h']).round(2) %>%</span> 1H</p>
              <% end %>
              
              <%# 24 Hr Change %>
              <% if (crypto_coin['quote']['USD']['percent_change_24h']) >= 0 %>
                <p><span class='up'><i class='fas fa-arrow-up' ></i>
                <%= (crypto_coin['quote']['USD']['percent_change_24h']).round(2) %>%</span> 24H</p>
              <% else%>
                <p><span class='down'><i class='fas fa-arrow-down' ></i>
                <%= (crypto_coin['quote']['USD']['percent_change_24h']).round(2) %>%</span> 24H</p>
              <% end %>

              <%# 7 Day Change %>
              <% if (crypto_coin['quote']['USD']['percent_change_7d']) >= 0 %>
                <p><span class='up'><i class='fas fa-arrow-up' ></i>
                <%= (crypto_coin['quote']['USD']['percent_change_7d']).round(2) %>%</span> 7Day</p>
              <% else%>
                <p><span class='down'><i class='fas fa-arrow-down' ></i>
                <%= (crypto_coin['quote']['USD']['percent_change_7d']).round(2) %>%</span> 7Day</p>
              <% end %>
            </div>

            <div class='crypto-individual-portfolio'>
              <div>
                <p class='p-no-gap'>Amount Owned</p>
                <%= crypto.amount_owned %>
              </div>
              <div class='crypto-line'></div>
              <div>
                <p class='p-no-gap'>Value USD</p>
                $ <%= crypto.amount_owned * crypto_coin['quote']['USD']['price'].round(2) %>
              </div>
            </div>

          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  
  
  
  
  
  
  
  
  
  <div class='crypto-index'>
    <table>
      <thead>
        <tr id='crypto-index-header'>
          <th>Name</th>
          <th>24HR</th>
          <th>Current Value</th>
          <th>Total</th>
        </tr>
      </thead>

      <tbody>
        <% @cryptos.each do |crypto| %>
          <tr>
            <% @crypto_coins.each do |crypto_coin| %>
              <% if crypto.symbol == crypto_coin['symbol'] %>
                <%# Crypto Name %>
                <td><%= link_to crypto_coin['name'], crypto, class: 'crypto-link' %></td>
                <%# 24 Hr Change %>
                <td><%= (crypto_coin['quote']['USD']['percent_change_24h']).round  %>%</td>
                <%# Total Value %>
                <td><%= number_to_currency(crypto_coin['quote']['USD']['price'].to_d * crypto.amount_owned) %>
              <% end %>
            <% end%>
            </td>
            <td><%= crypto.amount_owned %></td>


          </tr>
        <% end %>
        <tr id='crypto-index-header'>
      </tbody>
      
    </table>

    <br>


    
    <strong>Portfolio Profit/Loss: <%= number_to_currency(@portfolio_profit) %> </strong>
    <br>
    <br>
    <%= link_to 'New Crypto', new_crypto_path, class: 'btn btn-primary' %>

  </div>
</div>

app/views/cryptos/new.html.erb
<%= render 'form', crypto: @crypto %>

app/views/cryptos/show.html.erb
<p>
  <strong>Symbol:</strong>
  <%= @crypto.symbol %>
</p>

<p>
  <strong>User:</strong>
  <%= @crypto.user_id %>
</p>

<p>
  <strong>Cost per:</strong>
  <%= @crypto.cost_per %>
</p>

<p>
  <strong>Amount owned:</strong>
  <%= @crypto.amount_owned %>
</p>

<%= link_to 'Edit', edit_crypto_path(@crypto) %> |
<%= link_to 'Back', cryptos_path %>
<%= link_to 'Destroy', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %>

<% for purchase in @purchases %>
  <div>
    <p>
      <%= purchase.total_cost %>
    </p>
  </div>
<% end %>

app/views/home/about.html.erb
<h1>About</h1>
<%= @coins %>

app/views/home/index.html.erb
<% for coin in @coins %>
    <% for my_coin in @my_coins %>
        <% if my_coin == coin["symbol"] %>
            <%= coin["name"] %>: USD $<%= coin['quote']['USD']['price'] %><br>
            rank: <%= coin['cmc_rank'] %><br><br>
        <% end %>
    <% end %>
<% end %>

<%= @coins %>

app/views/home/lookup.html.erb
<h3>Crpyto Currency Lookup</h3>

<%= form_tag home_lookup_path, :method => 'POST' do %>
    <%= text_field_tag 'symbol', nil, placeholder: 'Enter Cryptocurrency Symbol' %>
    <%= submit_tag 'Lookup Crypto Quote' %>
<% end %>


<%= @symbol %>
<% if @symbol %>
    <% for coin in @lookup_coin %>
        <% if @symbol == coin["symbol"] %>
            <%= coin["name"] %>: USD $<%= coin['quote']['USD']['price'] %><br>
            rank: <%= coin['cmc_rank'] %><br><br>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class='alert alert-warning alert-dismissible'>
        <button class='close' data-dismiss='alert'>
            <i class='glyphicon glyphicon-remove-circle'></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Currency Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'navbar/navbar' %>

      <%= render 'layouts/flash'%>
      <%= yield %>
  </body>
</html>

app/views/navbar/_navbar.html.erb
 <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container">

        <!-- Brand -->
        <%= link_to 'Crypto Portfolio', root_path, class: 'nav-brand' %>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <%= link_to 'About', home_about_path, class: 'nav-link' %>
                </li>

                <li class="nav-item">
                    <%= link_to 'Lookup', home_lookup_path, class: 'nav-link' %>
                </li>

                <% if user_signed_in? %>

                    <li class="nav-item">
                        <%= link_to 'My Crypto', cryptos_path, class: 'nav-link' %>
                    </li>

                    <li class="nav-item">
                        <%= link_to 'New Purchase', new_purchase_path, class: 'nav-link' %>
                    </li>

                    <li class="nav-item">
                        <%= link_to 'History', purchases_path, class: 'nav-link' %>
                    </li>

                    <!-- User Account Things -->
                    <li class="nav-item">
                        <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Account', edit_user_registration_path, class: 'nav-link' %>
                    </li>

                <% else %>
                    <!-- User Account Things -->
                    <li class="nav-item">
                        <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
                    </li>
                <% end %>
            </ul>
        </div>

    </div>
</nav> 

app/views/purchases/_form.html.erb
<div class='purchase-form'>
  <div class='purchase-form-container'>
    <div class=purchase-form-form>
      
      <% if purchase.new_record? %>
        <h2>New Transaction</h2>
      <% else %>
        <h2>Edit Transaction</h2>
      <% end %>
      
      <%= form_with(model: purchase, local: true) do |form| %>
        <% if purchase.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

            <ul>
              <% purchase.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>


        <div class='purchase-form-radio'>


          <div class='purchase-form-radio-inner'>
            <div class='purchase-form-radio-option'>
            <%= form.label :description, 'Buy', :value => 'Buy' %>
            <%= form.radio_button :description, 'Buy' %>
            </div>
            <div class='purchase-form-radio-option'>
            <%= form.label :description, 'Sell', :value => 'Sell' %>
            <%= form.radio_button :description, 'Sell' %>
            </div>
            <div class='purchase-form-radio-option'>
            <%= form.label :description, 'Move', :value => 'Move' %>
            <%= form.radio_button :description, 'Move' %>
            </div>
          </div>
        </div>


        <div class="field">
          <%= form.label :symbol %>
          <%= form.text_field :symbol, placeholder: 'Symbol eg, BTC, XRP..' %>
        </div>

        <div class="field">
          <label>Cryptocurrency price</label>
          <%= form.text_field :cost_per, id: 'purchasePrice', placeholder: 'Price at time of transaction'%>
        </div>

        <div class="field">
          <label>Amount</label>
          <%= form.text_field :amount, id: 'purchaseAmount', placeholder: 'Amount of crypto involved' %>
        </div>

        <div class="field">
          <label>Fee Charged</label>
          <%= form.text_field :fee, id: 'purchaseFee', placeholder: 'Transaction fee' %>
        </div>

        <div class="field">
          <label>Total Value</label>
          <%= form.text_field :total_cost, id: 'purchaseTotal', placeholder: 'Total value' %>
        </div>


        <div class="actions">
          <% if purchase.new_record? %>
            <%= form.submit 'Create Transaction', class: 'purchase-form-btn', id: 'purchase-form-btn' %>
            <p>Don't wait to create a transaction? <a href="<%= purchases_path %>">Go Back</a></p>
          <% else %>
            <%= form.submit 'Edit Transaction', class: 'purchase-form-btn', id: 'purchase-form-btn' %>
            <p class='text-center'>Don't wait to edit this transaction? <a href="<%= purchase_path(purchase) %>">Go Back</a></p>
          <% end%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/purchases/edit.html.erb
<%= render 'form', purchase: @purchase %>

app/views/purchases/index.html.erb
<div class='purchase-container'>
  <div class='purchase-overview'>
    <h1>Transactions</h1>
    <%= link_to 'New Transaction', new_purchase_path, class: 'purchase-btn' %>
  </div>

  <div class='purchase-purchases'>
    <% for purchase in @purchases %>
      <div>
        <div class='purchase-card'>
          <div class='purchase-card-top'>
          <h3><% if purchase.description == 'Buy' %>
                Bought       
              <% elsif purchase.description == 'Sell'%>
                Sold
              <% else %>
                Moved
              <% end %>
          </h3>

          <% if File.exist?("#{@file}/color/#{purchase.symbol.downcase}.png") %>
            <%= image_tag("color/#{purchase.symbol.downcase}.png", :class => 'purchase-img')%>
          <% else %>
          <%= purchase.symbol %>
          <% end %>
          </div>

          <div class='purchase-amount'>
            <p><%= purchase.description == 'Buy' ? '+' : '-' %>
            <%= purchase.amount %></p>
          </div>

          <div class='purchase-card-description'>
            <div><p>$<%= purchase.total_cost %></p></div>
            <div><small><%=  purchase.created_at.strftime("%d-%b")%></small></div>
          </div>

          <a href="<%= purchase_path(purchase) %>">
          <span></span></a>  
        </div>
      </div>
      

      
    <% end %>
  </div>
</div>

app/views/purchases/new.html.erb
<div class='purchase-form'>
<%= render 'form', purchase: @purchase %>
</div>

app/views/purchases/show.html.erb
<div class='purchases-show'>
  <div class='purchases-show-container'>




    <div class='purchases-show-header'>
    <strong>
      <% if @purchase.description == 'Buy' %>
        Bought
      <% elsif @purchase.description == 'Sell' %>
        Sold
      <% else %>
        Moved
      <% end %>
      <% if File.exist?("#{@file}/color/#{@purchase.symbol.downcase}.png") %>
        <%= image_tag("color/#{@purchase.symbol.downcase}.png", :class => 'purchase-img')%>
      <% end %>
    </strong>
    </div>

    <div class='purchases-show-date'>
      <small><%= @purchase.created_at.strftime("%d-%b-%Y")%></small>
    </div>

    <div>
    <p>
      <strong>Crypto Symbol:</strong>
      <%= @purchase.symbol %>
    </p>
    </div>
    
    <div>
    <p>
      <strong>Cost per:</strong>
      $<%= @purchase.cost_per %>
    </p>
    </div>
    
    <div>
    <p>
      <strong>Amount:</strong>
      <%= @purchase.amount %>
    </p>
    </div>
    
    <div>
    <p>
      <strong>Fee:</strong>
      $<%= @purchase.fee %>
    </p>
    </div>
    
    <div>
    <p>
      <strong>Total Cost:</strong>
      $<%= @purchase.total_cost %>
    </p>
    </div>
    
    <div class='purchases-show-btn-container'>
      <%= link_to 'Back', purchases_path, class: 'purchase-show-btn btn-back' %>

      <%= link_to 'Edit', edit_purchase_path(@purchase), class: 'purchase-show-btn' %> 
      
      <%= link_to 'Delete', @purchase, method: :delete, data: {confirm: 'Are you sure?'}, class: 'purchase-show-btn' %>
    </div>
  </div>
</div>